### PR TITLE
number of winners added to history

### PR DESCRIPTION
**Pull request by Doomhammer458**
get all winner and count winners functions added

can use get_all_winners() to get names of all current and past winners. 

count_winners() returns the number of current and past winners.

number of winners has been added to the history message.

### CODE REVIEW

**Comment by bigdred777** [comment]
why wont this automatically merge?   could it be because i changed the text of the winners PM a few minutes ago?

**Comment by Doomhammer458** [comment]
yeah I'm manually merging is no big deal.

**Comment by bigdred777** [comment]
when i changed the text it merged it automatically. is there a way so that its not automatic so you can look at it and approve?

**Comment by Doomhammer458** [comment]
no idea..... i don't know how or why its pushing commits on your end.

the problem was i made changes without first making sure my branch was up to date, so it got confused with two branches with different values in some places.

but after i pulled your changes to my branch it was able to merge.

**Comment by bigdred777** [comment]
aaaah ok.

**Pull request merged**
